### ISSUE TITLE
[EPIC]: Improvments 

### ISSUE THREAD

**Issue by nashqueue** [rollkit/docs#200]
```[tasklist]
### Tasks
- [ ] #199
- [ ] #185
- [ ] #198
- [ ] pick new fonts for the site, and update existing graphics for this
- [ ] #203
- [ ] #202
- [ ] #219 
- [ ] #214 
- [ ] #209
- [ ] #196
- [ ] #220 
- [ ] #221
- [ ] #248 
- [ ] #244 
- [ ] #240 
- [ ] #239 
- [ ] #238 
- [ ] #235 
- [ ] #233
- [ ] #231 
- [ ] #230 
- [ ] #228 
- [ ] #225 
- [ ] #224 
- [ ] #223 
```
```[tasklist]
### Brand
- [ ] Logo Guideline
- [ ] Colour Scheme Guideline
- [ ] Typography Guidlines
- [ ] Illustrations
- [ ] Icon Guidlines
```

```[tasklist]
### Ideas
- [ ] https://github.com/rollkit/docs/issues/246
- [ ] https://github.com/rollkit/docs/issues/251
- [ ] https://github.com/rollkit/docs/issues/252
```

**Comment by Roockeeeet** [comment]
#200 develop in main
