### ISSUE TITLE
[Poktroll Feedback] Umbrella ticket for feedback from the Pocket Network Protocol team at GROVE

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#282]
From @Olshansk:

Going to share some feedback/suggestions for potentially improving the docs (before I forget). I'd make the PR myself but just not enough time to commit to sit down and do a good job on it.

- [x] "The `Polaris EVM rollup` contains some details that anyone needs to deploy a rollup but it is not something I read through or had the inkling of needing to read through. The `full and sequencer node rollup setup` section under `Advanced` is a good start but it'd be helpful to have a `instructions to deploy your sequencer to mocha testnet` section as well (covering some of the questions we had above)." (**NOTE: this is completed in** #290)
  - (a) noted feedback on Polaris guide. the details are useful for others, so they will be left in for now. (b) re: `instructions to deploy your sequencer to mocha testnet`, sounds like a good idea. to pull this guide from within the existing tutorial
- [x] "How to select a namespace isn't very clear, so I suggest having a helper similar to: `NAMESPACE_ID=$(echo -n $NAMESPACE_NAME | openssl dgst -sha256 -binary | head -c 8 | xxd -p)`"
  - what does this helper do differently?
- [x] "Add a link to the testnet faucet [1] with a copy-paste `$request <addr>` command to make it easier for the devs."(**NOTE: this is celestia-specific, and done on the testnet pages linked to already. running and funding node should be referenced in celestia docs. also since the testnet faucet for mocha is in discord, I think we should leave it this way for now. unless user is in the discord already, it won't take them to the channel**)
- [x] "In order to verify that things are working, suggesting an explorer (e.g. [celenium.io](http://celenium.io/)) where you can enter your namespace and validate it's running was a great source of truth to validate our assumptions."
  - good idea. mocha.celenium.io for mocha and [TBD] for arabica

**Comment by jcstein** [comment]
1. (a) noted feedback on Polaris guide (b) re: `instructions to deploy your sequencer to mocha testnet`, sounds like a good idea. to pull this guide from within the existing tutorial
2. what does this helper do differently?
3. since the testnet faucet for mocha is in discord, I think we should leave it this way for now. unless user is in the discord already, it won't take them to the channel
4. this is also a great idea!

**Comment by Olshansk** [comment]
Improve documentation related to consensus configurations:

Rollkit leverages the Cosmos SDK, which leverages CometBFT (formely known as Tendermint). However, Tendermint/CometBFT configurations are overriden, which can lead to some confusion.

Adding an Admonition that explicitly says (please paraphrase) the following could save devs a lot of time:
Look here:
- https://github.com/rollkit/rollkit/blob/main/config/config.go
Don't look here:
- https://docs.tendermint.com/v0.33/tendermint-core/configuration.html
- https://docs.ignite.com/nightly/references/cli
