### ISSUE TITLE
EPIC: docs improvements

### ISSUE THREAD

**Issue by jcstein** [rollkit/docs#356]
```[tasklist]
### Tasks
- [ ] Minimize steps in the tutorials
- [ ] Minimize software packages to be installed in the first few tutorials
- [ ] Create a tutorial for `rollkit start` make a quick start guide that uses the CLI
- [ ] Create a tutorial for just getting tokens on the cosmwasm testnet
- [ ] Add docs around the improved CLI
- [ ] Cut out what is not necessary due to improved CLI (as an example, the existing gm tutorial will be changed up a lot)
- [ ] Continue to implement diataxis.fr in the docs
- [ ] Consider switching frameworks
- [ ] Create a sandbox environment for docs
- [ ] Streamline CLI installation similar to `bash -c "$(curl -sL https://docs.celestia.org/celestia-node.sh)"`
- [ ] local explorer packaged in a CLI
- [ ] Revise "about rollkit" page
- [ ] add diagrams, beginning with excalidraw diagrams
- [ ] add specs to menu rollkit.github.io/rollkit
- [ ] remove the glossary
- [ ] remove the tutorial overview page
- [ ] make repos of demos/tutorials where appropriate. clean commits e.g. "feat: step 1"
- [ ] edit or remove readme page to reduce duplicate infos
```

**Comment by jcstein** [comment]
# tutorial funnel

1. CosmWasm/Rollkit testnet
2. Get coins from a faucet, and use the CLI to interact with the token and rollup
3. Make your own chain with a token and own name
4. Use ibc between testnets
5. IBC connection guide to the Rollkit testnet with your custom chain
6. Make the token do something
7. Make the token do something more complex
8.

**Comment by jcstein** [comment]
# da onboarding ideas

1. Remove light node for the quickstart tutorials, use a reliable RPC instead. Requires fewer dependencies
2. Then add a light node into the setup
3. Alternatively, build in celestia-node into the Rollkit CLI and allow some infrastructure to auto-fund the account that is used
4.

**Comment by Manav-Aggarwal** [comment]
Add how to guides for:

1. Turn your cometBFT app into a rollkit app
2. Use ignite to create a rollkit app

**Comment by jcstein** [comment]
🫡 https://github.com/rollkit/docs/issues/444
happy to close this issue, too, if it helps to make a new one for new quarter, etc.
