### ISSUE TITLE
[EPIC] Docs Restructure

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#480]
I  think there are the following user paths:

1. Running a rollup with the rollkit CLI
2. Building a rollup
3. Integrating with components (da, sequencing, execution)
4. Orchestration DevX

For 1, we have the quick start
For 2, we have wordle
For 3, I think it gets messy, because it is using GM, which jumped right into 4
For 4, We have kurtosis via the GM tutorial and the wordle tutorial, but this might not be the best place for it.

I’m wondering if for 3, we should use the quick start guide instead of GM. Then it is super clean and clear what is new with the DA integration for example.

For 4, we could have a Putting it all Together section at the bottom of the tutorial that is wordle with some base case, like Celestia DA, based sequencing, and the equivalent execution.

I think the GM tutorial is now a little out of place based on the above.
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/docs/pull/481
- [ ] https://github.com/rollkit/docs/issues/483
- [x] remove kurtosis from wordle
- [x] Create managing nodes section (infrastrucutre? DockerCompose)
- [ ] https://github.com/rollkit/docs/pull/493
- [ ] https://github.com/rollkit/rollkit/issues/1886
- [ ] https://github.com/rollkit/docs/issues/500
```

**Comment by MSevey** [comment]
Based on learnings around how Kurtosis handles data persistence and that it is not recommended for production, I will be removing it from the docs and focusing on production ready infrastructure management.

Plan is to focus on creating helpful docker compose files since those are fine for single rollup management. It will also serve as a framework for those that plan to manage multiple rollups.

**Comment by MSevey** [comment]
Closing this to just tracking the remaining clean up issues
