### ISSUE TITLE
Remove GM tutorial

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#483]
```[tasklist]
### Tasks
- [ ] https://github.com/rollkit/docs/issues/484
- [ ] https://github.com/rollkit/docs/issues/485
- [x] Remove GM Kurtosis from CosmWasm Tutorial
- [ ] https://github.com/rollkit/docs/pull/489
- [ ] https://github.com/rollkit/docs/pull/491
```

**Comment by MSevey** [comment]
Closing and tracking in individual follow up isses
