### ISSUE TITLE
Convert avail DA to use quick start guide

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#484]
```[tasklist]
### Tasks
- [ ] Run avail light node
- [ ] Test with quick start
- [ ] update tutorial
- [ ] https://github.com/rollkit/avail-da/issues/57
```

**Comment by MSevey** [comment]
## Update Run Avail Light Node

Updated the docs on local branch to reference avail documentation.
Running light client with `availup`
Lock in turing testnet
Seems that you can just submit blocks and don't need to fund an address? 


Try moving right to quickstart

**Comment by MSevey** [comment]
## Quick Start vs GM

It seems that the main difference from a tutorial perspective between the quick start and GM is how the go-da interface is used. 
Quick start works for nodes that integrate go-da directly, i.e. local da and celestia node. 
GM is needed for avail because avail light clients don't have go-da integrated directly, but use avail-da implementation of go-da.

**Comment by MSevey** [comment]
## Update

The tutorial needs to be updated to make it more clear that you need to be running an Avail Light Client and the Avail DA server. 

The DA tutorial section could use an overview page that explains this as well and how some DAs like celestia can integrate go-da directly, vs other DAs that need a DA server to proxy the interface. 

Running the avail tutorial against the Turing testnet gives DA submission errors https://github.com/rollkit/avail-da/issues/57

Running locally is a pain.... lots of nodes to run, long install times...

I've made some updates on a branch to the avail tutorials to track some of these changes but waiting to push them until I have it working either locally or on Turing testnet.
