### ISSUE TITLE
Convert how to guides to use quick start or wordle

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#485]
```[tasklist]
### Tasks
- [x] compare rollkit start commands for quick start and wordle
- [x] Update guides to be able to use either quick start or wordle if possible
- [ ] https://github.com/rollkit/docs/pull/490
- [x] Remove GM from Use Ignite to create a Rollkit app
- [x] Remove GM from Change speed of block production
- [x] Remove GM from zkml?? Verify if needed
- [ ] https://github.com/rollkit/docs/issues/519
- [x] Remove old GM files so they don't show up in search https://github.com/rollkit/docs/pull/489
- [ ] https://github.com/rollkit/docs/pull/491
- [ ] https://github.com/rollkit/docs/pull/511
- [ ] https://github.com/rollkit/docs/pull/515
- [ ] https://github.com/rollkit/docs/issues/520
```

**Comment by MSevey** [comment]
Run Full node guide steps don't work. Command has old flags, not sure what minimal flags need to be.

**Comment by MSevey** [comment]
Add clearing state to restart rollup

from the data directory, delete everything but the json file

├── data
│   ├── application.db
│   ├── priv_validator_state.json
│   ├── rollkit
│   └── snapshots

**Comment by MSevey** [comment]
Genesis guide needs to reference the file

**Comment by MSevey** [comment]
closing and tracking in sub issues.
