### ISSUE TITLE
IBC Guide Updates and Remove GM

### ISSUE THREAD

**Issue by MSevey** [rollkit/docs#520]
There is some overlap with the IBC how to guides. 

The IBC connection guide is pretty outdated using the local-celestia-devnet. 

The guides should cover the following:
1. Use IBC token as gas (in this case, TIA)
2. Establish an IBC connection (connect to mocha)

Parts that can be split out are setting up the IBC relayer. Unless there are rollkit specific steps, this should be scripted for simplicity. 

Verifying the IBC transaction on a block explorer should be captured. 

```[tasklist]
### Tasks
- [ ] Remove GM Reference and put in wordle
- [ ] Combine guides / re-order side bar
- [ ] Verify accuracy / link to compat version of mocha
```

**Comment by MSevey** [comment]
Open question: Is IBC enabled with cosmos-sdk-starter? Guides still reference cosmos-sdk fork

**Comment by tac0turtle** [comment]
closing this as the tutorial will include ibc
